### ISSUE TITLE
API event callback crash

### ISSUE THREAD

**Issue by skreberem** [nabto/edge-client-swift#2]
`ConnectionEventListener.apiEventCallback(ec:)` will crash if event callback modifies `userCbs` list by calling `removeUserCb(_:)`. Hash table can not mutate while being enumerated.
```
let callbacks = userCbs.allObjects
for cb in callbacks {
}
```

**Comment by gammelby** [comment]
... pod has been deployed, please use version **1.1.2** (not 1.1.1 as suggested above)
